// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xaqzisvydglrczbzmbpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhcXppc3Z5ZGdscmN6YnptYnB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzODU0MjMsImV4cCI6MjA2MDk2MTQyM30.ueT4e7IjDC8WKKzFf7cSvmpQoBhBg2eCjnqKMBllp80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);